language: bash
services: docker


env:
  global:
    image=eclecticiq/ansible
  matrix:
  - version=2.0.1.0
  - version=2.1.6.0
  - version=2.2.3.0
  - version=2.3.3.0
  - version=2.4.6.0
  - version=2.5.14
  - version=2.6.12
  - version=2.7.6

before_script:
  - tag=`echo $version | cut -d . -f -2`

script:
  - travis_retry docker build --build-arg VERSION=$version --tag "$image:$tag" .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push $image;
    fi
